@baseUri=http://localhost:{{$dotenv PORT}}
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJuYW1lIjoiMzI2YjcyYzdiNTRiNGQwMzkyOTgyZGI5ODUxZDc3OTMiLCJlbWFpbCI6Im5vZWxsZS5iYXJuZXNAZW1haWwuY29tIiwidXNlcm5hbWUiOiJub2VsbGUuYmFybmVzIiwiYWN0aXZlIjp0cnVlLCJhdmF0YXIiOiJodHRwczovL2kucHJhdmF0YXIuY2MvMzAwIiwiY292ZXIiOiJodHRwczovL2ltYWdlcy51bnNwbGFzaC5jb20vcGhvdG8tMTY4MjY4NzIyMDU2Ni01NTk5ZGJiZWJmMTE_cT04MCZ3PTgwMCIsIm90cEVuYWJsZWQiOnRydWUsIm90cFZlcmlmaWVkIjp0cnVlLCJvdHBWYWxpZGF0ZWQiOnRydWV9LCJpYXQiOjE3MDgzNTk1MTYsImV4cCI6MTcxMDk1MTUxNiwiYXVkIjoiQ1JVRCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsInN1YiI6Im5vZWxsZS5iYXJuZXMifQ.VGnjYB1FPaS3OIuFh812KzBnRy-kA7p-CmWFbf5afqg
@username=noelle.barnes
@password=A1noelle.barnes

### Get user
GET {{baseUri}}/api/v1/users/{{username}}
Authorization: {{token}}

###  List user
GET {{baseUri}}/api/v1/users/?page=1&size=10
Authorization: {{token}}

### Create user
POST {{baseUri}}/api/v1/users/
Authorization: {{token}}
Content-Type: application/json

{
  "name": "{{$guid}}",
  "username": "{{$guid}}",
  "password": "{{password}}"
}

### 
PATCH  {{baseUri}}/api/v1/users/{{username}}
Authorization: {{token}}
Content-Type: application/json

{
  "patch": [
    { "op": "replace", "path": "/active", "value": true }
  ]
}